### ISSUE TITLE
Errors can crop up if number of arguments change in procedure used in relationships

### ISSUE THREAD

**Issue by qiemem** [arthurhjorth/LevelSpaceXWGUI#56]
Adding args can result in errors while running relationships if you don't resave them first.

Removing args error when redisplaying the relationships.

**Comment by qiemem** [comment]
Error from removing (`n` was the removed argument name):

```
java.util.NoSuchElementException: key not found: n
 at scala.collection.MapLike$class.default(MapLike.scala:225)
 at scala.collection.immutable.ListMap.default(ListMap.scala:51)
 at scala.collection.MapLike$class.apply(MapLike.scala:135)
 at scala.collection.immutable.ListMap.apply(ListMap.scala:51)
 at org.levelspace.LSArgumentSelector$$anonfun$selectedArgumentIndices_$eq$1.apply(LSArgumentSelector.scala:33)
 at scala.collection.Iterator$class.foreach(Iterator.scala:772)
 at scala.collection.immutable.VectorIterator.foreach(Vector.scala:648)
 at org.levelspace.LSArgumentSelector.selectedArgumentIndices_$eq(LSArgumentSelector.scala:29)
 at org.levelspace.RelationshipKind$$anonfun$36.apply(RelationshipWidget.scala:67)
 at org.levelspace.RelationshipKind$$anonfun$36.apply(RelationshipWidget.scala:67)
 at uk.ac.surrey.xw.api.Property$$anonfun$set$1.apply(Property.scala:37)
 at uk.ac.surrey.xw.api.Property$$anonfun$set$1.apply(Property.scala:37)
 at scala.Option.foreach(Option.scala:197)
 at uk.ac.surrey.xw.api.Property.set(Property.scala:37)
 at uk.ac.surrey.xw.api.ExtraWidget$$anonfun$setProperty$1.apply(ExtraWidget.scala:26)
 at uk.ac.surrey.xw.api.ExtraWidget$$anonfun$setProperty$1.apply(ExtraWidget.scala:25)
 at scala.Option.foreach(Option.scala:197)
 at uk.ac.surrey.xw.api.ExtraWidget$class.setProperty(ExtraWidget.scala:25)
 at org.levelspace.Relationship.setProperty(RelationshipWidget.scala:107)
 at uk.ac.surrey.xw.gui.GUI$$anonfun$uk$ac$surrey$xw$gui$GUI$$setProperty$1.apply(GUI.scala:76)
 at uk.ac.surrey.xw.gui.GUI$$anonfun$uk$ac$surrey$xw$gui$GUI$$setProperty$1.apply(GUI.scala:76)
 at scala.Option.foreach(Option.scala:197)
 at uk.ac.surrey.xw.gui.GUI.uk$ac$surrey$xw$gui$GUI$$setProperty(GUI.scala:75)
 at uk.ac.surrey.xw.gui.GUI$$anonfun$notify$2.apply$mcV$sp(GUI.scala:49)
 at uk.ac.surrey.xw.gui.GUI$$anonfun$notify$2.apply(GUI.scala:49)
 at uk.ac.surrey.xw.gui.GUI$$anonfun$notify$2.apply(GUI.scala:49)
 at uk.ac.surrey.xw.api.package$$anon$1.run(package.scala:28)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
 at java.awt.EventQueue.access$400(EventQueue.java:82)
 at java.awt.EventQueue$2.run(EventQueue.java:676)
 at java.awt.EventQueue$2.run(EventQueue.java:674)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```
